version: '3.9'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  web_app:
    build: .
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - 4089:4000
    volumes:
      - .:/app
volumes:
  pgdata: